"""Generate, audit (E0) and write a SYNTHETIC development dataset.

Usage (from the repository root, after `pip install -e .` or with PYTHONPATH=src):
    python scripts/generate_synthetic.py [--config configs/synthetic/development_v1.yaml]

Writes data/synthetic/development/<dataset_version>.csv and a matching
.manifest.json. Refuses to overwrite an existing file whose contents differ.
Exit code 1 on any audit or reproducibility failure.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from agnidrish.audit import AuditError, check_reproducible, run_audit
from agnidrish.synthetic.config import load_config
from agnidrish.synthetic.generator import GENERATOR_VERSION, generate

REPO_ROOT = Path(__file__).resolve().parents[1]
log = logging.getLogger("generate_synthetic")

CATEGORY_NOTE = (
    "SYNTHETIC methodology-validation data generated by AgniDrishti. NOT official SIH/ISRO data; "
    "does not reproduce the hidden SIH evaluation. Families, anomaly labels, severity and splits "
    "are the project's experimental definitions. Held-out families 19-20 are not included."
)


def git_state() -> dict[str, object]:
    def run(*args: str) -> str:
        return subprocess.run(["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, check=True).stdout.strip()

    tracked = ("src", "configs", "scripts", "pyproject.toml")  # everything that determines the data
    return {"commit": run("rev-parse", "HEAD"), "dirty": bool(run("status", "--porcelain", "--", *tracked))}


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", default="configs/synthetic/development_v1.yaml")
    parser.add_argument("--out-dir", default="data/synthetic/development")
    args = parser.parse_args()

    config_path = (REPO_ROOT / args.config).resolve()
    out_dir = (REPO_ROOT / args.out_dir).resolve()
    config = load_config(config_path)
    log.info("generating %s", config.dataset_version)
    table = generate(config)

    try:
        report = run_audit(table, config)
        check_reproducible(table, config)
    except AuditError as err:
        log.error("%s", err)
        return 1

    csv_bytes = table.to_csv(index=False, lineterminator="\n").encode("utf-8")
    digest = hashlib.sha256(csv_bytes).hexdigest()
    out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = out_dir / f"{config.dataset_version}.csv"
    if csv_path.exists() and hashlib.sha256(csv_path.read_bytes()).hexdigest() != digest:
        log.error("%s exists with different contents; bump the config version instead of overwriting", csv_path)
        return 1
    csv_path.write_bytes(csv_bytes)

    reloaded = pd.read_csv(csv_path)
    try:
        run_audit(reloaded, config)
    except AuditError as err:
        log.error("written file fails the audit: %s", err)
        return 1

    manifest = {
        "data_category": "synthetic",
        "note": CATEGORY_NOTE,
        "dataset_version": config.dataset_version,
        "file": csv_path.name,
        "file_sha256": digest,
        "generator_version": GENERATOR_VERSION,
        "config_path": config_path.relative_to(REPO_ROOT).as_posix(),
        "config_sha256": config.sha256(),
        "seed": config.seed,
        "git": git_state(),
        "created_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "reproducibility": "regenerated in memory from config + seed: identical",
        "config": config.raw,
        "audit": report,
    }
    manifest_path = out_dir / f"{config.dataset_version}.manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, default=str) + "\n", encoding="utf-8")
    log.info("wrote %s (sha256 %s) and %s", csv_path.relative_to(REPO_ROOT), digest[:12], manifest_path.name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
